### ISSUE TITLE
Add `modular lint` command

### ISSUE THREAD

**Issue by NMinhNguyen** [jpmorganchase/modular#109]
See prior discussion in #90 and #108. Will require configurability to specify options such as the base branch (`main` / `master`) https://github.com/atlassian/changesets/blob/377f5c385ad9db4ff8458f159e2d452c39828567/packages/config/schema.json#L52-L56

**Comment by LukeSheard** [comment]
@cangarugula Let's target this for 1.2 using `jest-runner-eslint` by default.
