### ISSUE TITLE
Tests centre around `packages/app` even though they are run for the whole of `packages/*`

### ISSUE THREAD

**Issue by sebinsua** [jpmorganchase/modular#112]
<img width="386" alt="Screenshot 2020-09-24 at 12 58 31" src="https://user-images.githubusercontent.com/152098/94142206-ce07ef80-fe65-11ea-9ac8-98e2e6494783.png">

As you can see from the `../app-two/src/` above, the paths seem to be relative to `packages/app`.

I'm assuming this is because of the current working directory, so perhaps this should be changed? However I have a memory that `react-scripts` and `craco` were quite fussy about the directory they were run from so we will need to figure out how to do this.

Functionally, I don't think it presents a huge issue, but aesthetically it's gross. ~~(Actually, perhaps it might impact on the coverage, in which case it would be a functional concern...)~~

**Comment by threepointone** [comment]
Fixed in https://github.com/jpmorganchase/modular/pull/155
