### ISSUE TITLE
Self-hosting the project / dog-fooding

### ISSUE THREAD

**Issue by sebinsua** [jpmorganchase/modular#120]
We should [self-host the project](https://en.wikipedia.org/wiki/Self-hosting_(compilers)) and generally dog-food any code that we write within the project.

The philosophical reason for this would be to _"taste one's own medicine"_ but the practical reasons are much stronger:

- The only way we have to test everything right now is to publish it and then consume the packages as part of an E2E process. This is a very, very slow feedback loop -- and more fragile than I'd like on environment differences or incorrectly written tests, etc.
  - If you're writing test configuration or changing lint rules, we should be able to test these with our own `yarn test` or `yarn lint` command in only a few seconds, for example.
  - There should be a way to quickly create a Modular project and app from within this repository. We have all of the logic required to do so within the tests ([here](https://github.com/jpmorganchase/modular/blob/master/e2e-tests/core.test.ts#L24-L115) and [here](https://github.com/jpmorganchase/modular/blob/4ab966e38e50256ada5f2f7e7832ad80358a6e7b/e2e-tests/core.test.ts#L319-L332)). There's nothing stopping us from pulling this out into a script that a developer can quickly run within the project.
    - Potentially we could also have a `packages/app` (marked as `"private": true`) within the project which would mean people could test changes to `modular-scripts` without any tiresome initialisation of a new project.
- Actually, the E2E process itself is slow because there are multiple `yarn install`s involved in executing `create-modular-react-app`. Elsewhere we talk about caching `yarn install`s but we don't do that here which is why these tests take 6+ minutes to run, instead of taking < 1 minute.
  - If we have a performance problem within the project, it makes sense that we should use [whatever techniques are appropriate](https://github.com/jpmorganchase/modular/issues/62) to fix the problem. That would also be a good test that our tools and instructions related to this are good.
- It's quite weird that we're using different Jest/Lint configurations [in this project](https://github.com/jpmorganchase/modular/blob/master/.eslintrc.js) than the ones we use in [the output project](https://github.com/jpmorganchase/modular/blob/master/packages/eslint-config-modular-app/index.js). I think this was accidental and we should fix it.
- We have [dependencies within our root `package.json` which should actually belong to our packages](https://github.com/jpmorganchase/modular/issues/114).

This doesn't need to be done immediately: I'm just getting my thoughts down.

**Comment by threepointone** [comment]
Made some progress on this with https://github.com/jpmorganchase/modular/pull/132.
