### ISSUE TITLE
Leaky abstractions due to building on top of other tools

### ISSUE THREAD

**Issue by sebinsua** [jpmorganchase/modular#122]
We’re reconfiguring `create-react-app` using [`craco`](https://github.com/gsoft-inc/craco), but this doesn’t give us full control, and in some situations our choice is between ‘inlining more code into the repository and therefore increasing the maintenance cost’ and ‘improving the DX’.

For example:

* We can’t fix [the test paths](https://github.com/jpmorganchase/modular/issues/112), without being able to change the current working directory, and unfortunately [that causes `react-scripts test` to crash](https://github.com/facebook/create-react-app/blob/cbad256a4aacfc3084be7ccf91aad87899c63564/packages/react-scripts/scripts/test.js#L32).
* The way we initialise a project relies on us moving/deleting files created by the underlying tools, and this makes that code fragile to implementation details of the original tools. Additionally, in some cases, the behaviour we achieve is subtly incorrect but cannot be fixed. For example, [an `npm install` happens during a `yarn install` due to the way `react-scripts` detects a Yarn installation](https://github.com/jpmorganchase/modular/pull/117/files#r497072701).

These aren't super important and there is a large benefit to continuing to delegate this logic to upstream tools, however I would like to make any issues like this visible here so we can decide if/when to inline and fix a problem -- there might be a 'tipping point'.

**Comment by threepointone** [comment]
We now own the test runner and avoid the crash, so that's fixed. 

There's no clear workaround for the second issue ta the moment. 

Closing this issue in favour of any specific issues that can be filed in the future when they come to light.
