### ISSUE TITLE
Loaders and rehoming views/apps into a single repo

### ISSUE THREAD

**Issue by sebinsua** [jpmorganchase/modular#123]
_This is a high-level issue to discuss the overall goal of getting multiple teams to develop apps and views that are loaded into a dashboard-style application provided by a single repository._

---

Beyond [making bespoke application repositories Modular repositories (#115)](https://github.com/jpmorganchase/modular/issues/115) independently, the overall goal is, said to be, to provide a framework/toolchain for multiple teams to work effectively within a single repository.

A recent PR added in [support for building and starting multiple apps within a single repository (#67)](https://github.com/jpmorganchase/modular/issues/67), but the original idea was that [applications are code-split and loaded as views (previously "widgets") via a `viewsMap` that is automatically generated from the `packages/*` marked via `package.json#modular.type` as `"view"` (#59)](https://github.com/jpmorganchase/modular/issues/59).

Whatever the eventual implementation, as internal teams begin to use the framework, they will need to do work to load their applications/views.

It has been proposed that we work on 'loaders' to simplify doing so, however, getting the implementation correct for disparate apps will likely require invidividual team's effort, therefore:

- Can we write examples, guidance and documentation towards this end goal?
- Presumably, we wish different loader approaches to become more consistent. How will we achieve this, and what does this end goal look like?
- Can we do this iteratively?

**Comment by steveukx** [comment]
This conversation is quite stale, and may have been resolved at least in part by the inclusion of the new `esm-view` package type that generates an ES module for any view that can then be loaded into the "dashboard style" app using a micro-frontend style architecture.

If you feel this conversation should remain active, please do create a new issue.
