### ISSUE TITLE
Generate coverage reports from our tests 

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#146]
We should generate coverage reports from our own internal tests. I don't think we should have any rules regarding what percentage should be covered, but it would be nice to have some insight into it anyway. Further, it would be a good reference to whatever we eventually want to do with https://github.com/jpmorganchase/modular/issues/119.

**Comment by matt-d-webb** [comment]
Is this something @Cono52 would be the supreme SME on? haha :rofl:
