### ISSUE TITLE
react/react-dom (and other core dependencies) should be installed at the root 

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#149]
In modular projects, react/react-dom should probably be installed at the root if the project. This also prevents having to specify the package versions in created views ([which are lagging](https://github.com/jpmorganchase/modular/blob/510a8764409553d26b2736bf479585f25aa2e97a/packages/modular-scripts/types/view/package.json#L7-L8) behind the versions that create-react-app installs right now, 17 vs 16)

This also applies to typescript, tho maybe that be a separate PR, and might have a couple of other considerations.

**Comment by NMinhNguyen** [comment]
> This also prevents having to specify the package versions in created views

Would this not be an issue when using Yarn v2 (or any tool like ESLint for example that checks imports and dependencies)? When it comes to publishing packages, they'll need to properly declare their dependencies as well.

**Comment by threepointone** [comment]
Yeah, `modular package` will rewrite package.json to include those dependencies (as well as packages imported from local workspaces) when making build artifacts.

**Comment by threepointone** [comment]
Fixed in #167
