### ISSUE TITLE
pass environment variables correctly, always. 

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#150]
@LukeSheard  mentioned that CI=true wasn't being passed correctly in our CI environment. Similarly, in this test: https://github.com/jpmorganchase/modular/blob/510a8764409553d26b2736bf479585f25aa2e97a/packages/modular-scripts/src/__tests__/index.test.ts#L287-L288
I had to manually remove coloring bytes from the output string despite the fact that CI=true should be triggering that anyway. There maybe a path by which environment variables aren't being passed correctly. Will investigate.

**Comment by LukeSheard** [comment]
For testing specifically I think this is likely the issue? https://github.com/jpmorganchase/modular/blob/510a8764409553d26b2736bf479585f25aa2e97a/packages/modular-scripts/src/cli.ts#L249

**Comment by threepointone** [comment]
it's odd that it doesn't pass in existing environment variables, but I'm not knowledgeable enough to know what the expectation is. Regardless, should probably read and pass it it in explicitly to fix this problem. Will send a PR soon.

**Comment by threepointone** [comment]
I'm going to close this till it's an actual problem and we can say it's actually failing somewhere. This is too broad too act on.
