### ISSUE TITLE
Freshly generated project has broken test on Windows

### ISSUE THREAD

**Issue by Cono52** [jpmorganchase/modular#151]
Doesn't seem to be a problem on my Mac but decided to run on Windows in case everyone else wasn't.

I checked again, by pulling latest from master on both my machines -> rebuild -> re-add to global -> regenerate a test projects -> re-run tests

<img src="https://user-images.githubusercontent.com/10832455/99692330-1caac200-2a82-11eb-9b7c-4d53f6d6f83d.png" width="400">

i guess it's related to jest dom not being added correctly?

**Comment by threepointone** [comment]
Oh hmm, yeah, looks like setupTests isn't being called properly.

**Comment by Cono52** [comment]
I think it's related to the globby in the craco config.
seems globby has some catches on Windows.
https://github.com/sindresorhus/globby/issues/155

**Comment by threepointone** [comment]
We could just not use globby here https://github.com/jpmorganchase/modular/blob/510a8764409553d26b2736bf479585f25aa2e97a/packages/modular-scripts/craco.config.js#L88-L89
maybe like...
```jsx
[path.join(absoluteModularGlobalConfigsPath, 'setupTests.js'),
path.join(absoluteModularGlobalConfigsPath, 'setupTests.ts'),
path.join(absoluteModularGlobalConfigsPath, 'setupTests.tsx')].filter(p => fs.existsSync(p))
```

**Comment by threepointone** [comment]
We should also run our CI tests on windows, I'll look into that later.

**Comment by Cono52** [comment]
Your code sliced worked in the above case but it was handy to keep some globing to keep giving those nice warning about other "setupTests" files that might be found somewhere randomly in the package i.e.

https://github.com/jpmorganchase/modular/blob/510a8764409553d26b2736bf479585f25aa2e97a/packages/modular-scripts/craco.config.js#L72-L76
