### ISSUE TITLE
RFC: `modular build`: take 2

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#152]
Currently, we have a `build` command that given an app name, runs `react-scripts build` on it, and outputs the built assets into `packages/<name>/dist`. That's pretty good, and serves the original purpose of `modular`, i.e, building apps. 

I'd proposed earlier that without any changes to our design, we can use modualr to build libraries too, making `modular` a general software development pattern. (Previous proposal - https://github.com/jpmorganchase/modular/issues/49). This issue adds some more implementation details. 

- `modular build <name>`: 
  - should build the workspace named `<name>`. If it's an app, then it runs `react-scripts build` on it, nothing changes there, but it should move built assets to `<root>/dist/<name>`.

  - If it's a view or a regular package, then it should first run `yarn build` inside that workspace (delegating to any build command defined in its package.json), and then run a build script that generates a single esm file, a cjs file, and typings for that package. It then generates a .tgz of the package (with a modified package.son that points to these new assets), and moves it to `<root>/dist/<name>.tgz`. 

- `modular build <name1>,<name2>,<name3>`: Like the above, but runs multiple builds at once. 

- `modular build --all`: Runs builds on all workspaces.

- `modular build --changed`: Runs builds only on 'changed' workspaces, as defined by https://github.com/jpmorganchase/modular/issues/147.  

---

I'll send a PR for a base implementation of this very soon.

**Comment by threepointone** [comment]
We'll need a way for workspaces to opt-out of this flow, since there will be packages that might not want to built in this manner. Which probably means another field in the modular config  in the workspace's package.json.

**Comment by threepointone** [comment]
Work for this ongoing in https://github.com/jpmorganchase/modular/tree/build-2

**Comment by matt-d-webb** [comment]
What would the default be fore `modular build` (no input). Would it make sense for that to be `modular build --changed` as that is perhaps the most efficient?

**Comment by threepointone** [comment]
That sounds fair.

**Comment by threepointone** [comment]
I'm now of the opinion that we shouldn't have an `--all` command. It doesn't make sense in any codebase that's big enough to matter. And it's not hard to make a command that pipes all a directory's names to this command. 

Landed the build PR in https://github.com/jpmorganchase/modular/pull/195. We're tracking affected builds in https://github.com/jpmorganchase/modular/issues/147. So I'm closing this issue 🎉

**Comment by threepointone** [comment]
For posterity's sake, you can emulate `--all` with 
```
 yarn modular build `ls -m packages | sed 's/, /,/g'`
```
