### ISSUE TITLE
Issues with using package.json#bin

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/modular#1756]
Hi there,

I've got a package in a Modular-based monorepo (currently using `modular-scripts` v2.3.0) which contains a couple of scripts intended to be run as command-line tools. I therefore use the [`package.json#bin`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#bin) field so that when consumers install the package globally, the CLI scripts are automatically copied to a directory that's in their `PATH`.

However, I've run into a few issues I've had to work around (and one I have yet to resolve). Sharing them here in the hope that future versions of Modular will support this stuff right out of the box:

### 1) `bin` field not updated in build
When your source `package.json`'s `main` field points to a TypeScript source file, Modular will rewrite it in the build output's `package.json` to point to the corresponding CommonJS module.

I therefore assumed `bin` would work in a similar fashion, but it seems it just gets copied across as-is:

E.g.:

```jsonc
// source package.json
{
  "main": "src/index.ts"
  "bin": {
    "my-cool-app": "src/cli.ts"
  }
  // ...
}
```

Gets built to something like:

```jsonc
// dist package.json
{
  "main": "dist-cjs/index.js"
  "bin": {
    "my-cool-app": "src/cli.ts" // <-- now points to non-existent source file
  }
  // ...
}
```

Fortunately, the workaround for this is simple: I just make sure the paths in my source `#bin` field match what they will be in the build output. However, it would be neater if modular handled this for me. Also, if modular ever changes the naming or structure of the build output, things would continue to work whereas my hard-coded workaround would break in that scenario.

### 2) rollup barfs on hashbangs
My source TypeScript files that get compiled to CLI scripts have `#!/usr/bin/env node` hashbangs as their first lines, as per the instructions in the NPM docs:

>Please make sure that your file(s) referenced in bin starts with `#!/usr/bin/env node`, otherwise the scripts are started without the node executable!

This was giving me build errors which I eventually traced back to `rollup`. It seems that, out of the box, `rollup` doesn't support these hashbangs and therefore it reports a syntax error and breaks the build.

I found this plug-in that adds support for hashbangs to rollup: https://github.com/egoist/rollup-plugin-hashbang#readme

...and I was eventually able to make `modular-scripts` use the plug-in by patching it via `yarn patch`. Specifically, I `require()` the plug-in and add it to the rollup config inside Modular's `dist-cjs/build/buildPackage/makeBundle.js` file.

With this change, my CLI scripts would build without errors.

Obviously, patching modular isn't really sustainable. So perhaps future versions could either include this plug-in or provide some mechanism for users to extend the built-in rollup config.

### 3) hashbang is stripped from the output
While I do now get clean builds, for some reason my output files are missing the hashbang (therefore don't run as intended when invoked from the command line). I'm still investigating this, so not sure exactly why that is. Supposedly, `rollup-plugin-hashbang` should ensure that the hashbang is present in the build output. Perhaps I need to experiment with the order of plugins? I had placed it before the esbuild plugin, so maybe esbuild is stripping it away? Or does Modular do any post processing of the output files that might be doing this?

Any help or pointers on this one would be much appreciated. Thanks!

**Comment by cristiano-belloni** [comment]
Hello @james-nash, thanks for this report! Since you're already patching modular, would you mind submitting a PR that we can take a look at?

**Comment by LukeSheard** [comment]
As a heads up - this used to be supported in some very early versions of modular which had ambitions of being a generic package building tool. However the functionality was removed as modular became a `cli` with a focus on building for browsers and not node, this is because the requirements from a build tool are very different and have a completely different set of boundary conditions.

**Comment by james-nash** [comment]
@cristiano-belloni Apologies for the slow reply. I'm a bit swamped work-wise at the moment, so haven't gotten around to making a PR yet. However, you can see the patch code here https://github.com/jpmorganchase/uitk-workshop/blob/playground/.yarn/patches/modular-scripts-npm-3.0.2-cc4becbc6f.patch (it's a private repo but as a member of this org, I think you should be able to access it). That patch also does some other stuff (the `_swcPlugin`bits) which is unrelated, so ignore those. Hopefully that gives you a sense of what we've done.

@LukeSheard I'm open to _not_ using `modular` for this particular package if it's not the right tool for the job. However, the other packages in that monorepo are code for browsers. My CLI is a bit of an unusual case: It uses a library of React components (which is one of the other packages in that `modular` monorepo). However, those components render HTML intended to be shown in email clients. My CLI is a tool that uses a combination of MDX and `ReactDOMServer` to render email HTML and then send it. So, if that's a usecase the modular project would like to support, I'll try to make that PR. But if it's something you don't want to support then please go ahead and close this issue and I'll explore alternatives.

**Comment by cristiano-belloni** [comment]
@james-nash From Modular >4.0 we support non-Modular packages in a Modular monorepo and we're also able to use Modular as a task runner to build / test / lint them with their custom scripts in dependency order.

The officially recommended way of supporting a CLI Node tool is to create it as a non-Modular package and add a `build` script in your package.json (that will be called by `modular build [...packages] [--ancestors] [--descendants] [--changed]`)

We won't support CLI tools using Modular `package`s because packages are libraries intended to be run on the browser (bundled in an application), and have semantics (e.g. entrypoints) that are different from CLI tools.
