### ISSUE TITLE
custom lint rules 

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#181]
We have our lint config right now, which is just a wrapper around eslint-config-react-app. But we can also use that to enforce lint rules that are specific to modular. Opening this issue to gather suggestions for what rules to add. 

1. Libraries (Views/Packages) are not allowed to import from submodules of other workspaces (So `packages/lib1` can't import from `packages/lib2/src/something/else`). 
1.1 Unless that submodule is exported as a separate entrypoint. (TODO The feature doesn't exist yet). 
1.2 Apps don't have this restriction.
2. Users aren't allowed to use webpack specific implementation comments around dynamic imports .e.g `import(/* webpackPrefetch: foo*/ "./foo.js").then(() => {})` because we may decide not to use webpack.

**Comment by threepointone** [comment]
- (for packages that run on node) using __filename and __dirname to resolve might not be such a good idea, since it's likely that relative paths won't survive after being compiled. This should probably be an error, and workarounds should be documented.

**Comment by cristiano-belloni** [comment]
Since we already parse packages / apps / esm-view imports, we should probably do this, but not at lint level.
