### ISSUE TITLE
The case against workspaces

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#188]
Just so we're clear, workspaces are a tradeoff for organisations that are transitioning to bigger repository structures, and have only just started looking at multiple teams working in a single repository. In an 'ideal' world, there would only be one package.json in a repository, and only for third party dependencies. Some modules would be marked as entrypoints (in whatever way, maybe in a configuration file somewhere, or as frontmatter/pragma instructiions in the module itself, whatever). There would also be no need to have build/publish/release cycles fir artifacts, since every dependency would be in the same repository and would be referenced directly. Consequently, there would be no versioning hell either, since there aren't really any versions. 

There isn't much else to say here. It takes a culture/social structure to be able to achieve this, and tooling across the 'system' to have any semblance of velocity to move in this system. Workspaces and standardisations of build pipelines as such are a transition strategy to reach this end state, nothing more.

**Comment by Cono52** [comment]
If we are assuming apps/packages will always 'directly' reference their dependencies, as oppose to a released version hosted on a package registry;

as an app developer, for example, would I be forced to make fix any possible breaks caused by the package owners, whos package I'm directly referencing?

**Comment by threepointone** [comment]
The other way around, the package developer can't land their code if it's breaking your app's tests and/or types. 

This is how react ships from master multiple times a week to Facebook.com, the react team is responsible for making sure they haven't broken anyone else's code that depends on them.

**Comment by threepointone** [comment]
(But it also means package/library developers are free to come into your codebase and make changes as required, and you'd be added as a reviewer to their changes to your code).

**Comment by LukeSheard** [comment]
I think there's a strong argument here that we migrate from `package.json` to `modular.json` or something similar here. It could contain any metadata for the directory that's needed - and we could easily use something like `find -name modular.json` to quickly discover directories it the repository. 

For the case of finding apps to build - in our current monorepo we use a doc-string to achieve the same thing (something that's just parsed with Regex, but could be smarter).

```javascript
/*
 *  Flags: typescript-entry-point
 */
```

To address @Cono52 - yes that means that if you want to make a change you have to make sure that all apps which you affect compile + tests pass. This forces you to write good tests - because if your app breaks and there wasn't a test for it then you're going to look a bit embarrassed 😄

**Comment by Cono52** [comment]
ye sounds good, not having versions will enforce that no one gets left behind (ex. credit dashboard lagging behind versions of UI Toolkit ) and bring attention to lack of maintainers/resources on either side of that relationship.
making it more painful to do the wrong thing than the right thing.

**Comment by threepointone** [comment]
To clarify, we're months (honestly, years) away from this end-state at jpm, but who can tell. Stranger things have happened. And I don't really have anywhere else to be...

**Comment by threepointone** [comment]
The case against nesting workspaces (by team)
---

So, the suggestion came up to support another level of nesting inside `packages/`. The reasoning was that if we want to support proper "monorepos" and have multiple teams working in the same repository, then we should allow teams to have a top level folder for their stuff. So, workspaces would be `packages/*/*` in the root `package.json` the directory structure would look like this: 

```
packages
  @team-1
    app-1
    app-2
    view-1
    view-2
    pkg-1
    pkg-2
  @team-2
    app-1
    app-2
    ...
  ...
  @team-n
    ...    
```

My contention is that this doesn't solve a core problem, and actually exacerbates conway's law by siloing work by team. It's *slightly* better than our current situation in that you can at least grep for code, but what we want to actually do is silo work by _function_, not by _team_. Code isn't a stacked hierarchy but a graph, and a tree isn't actually the best representation for showing the relationship between modules. And setting this precedent will mean that _more_ levels will be asked for; if a team is really big, then they'll ask for another layer (like `team-1/team-1-1|team-1-2`), etc. I don't think that's good. 

What this points to, is that we're trying to use file structure to represent multiple concerns at once, with tools that aren't sufficient for even one of them. SO let's simplify. 

I suggest we still keep everything flat as we have now. We should use scopes to name both directories and packages. So it would look something like this

```
packages 
  @team-1-app-1 // package.name === @team-1/app-1
  @team-1-app-2 // package.name === @team-1/app-2
  ...
  @team-2-app-1
  @team-2-app-2
  ...
``` 

The length of this directory might seem too long to you, but... so what? Navigating happens with autocomplete/fuzzy search/etc anyway already. We're going to work on better visualisation/navigation tools for this repository, and we assume teams that care strongly will do sparse checkouts for slices of their codebase anyway. 

---

Y'know what, it would make sense to nest as you please if you *didn't* have to assign workspaces to specific points in the file structure. Just put code wherever, and reference it however. But because we're still dependent on having to publish versioned artifacts (libraries/views) with `package.json`s, we'll be stuck doing this flat thing for a while. It's fine.

**Comment by threepointone** [comment]
No action to take here for now, closing this issue.
