### ISSUE TITLE
Modular lacks some nice to haves for library publishers

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/modular#2160]
### Building
- [x] Auto-including license files (#2050 )
- [x] Auto-adding the repository field in the package.json (#2161 )

I discovered this when checking out socket https://socket.dev/npm/package/modular-scripts

You can see that modular is flagged because;

- No matching license files were found
- No linked source code repositories were found

Shipping the License sounds ideal since that is what contains the copyright notice.
Attaching source code repositories allows features like npm's linking to work e.g.

![image](https://user-images.githubusercontent.com/12938082/191944627-cfa4e643-7e0b-4df3-baaa-5215724d00a0.png)

Which is missing for modular:

![image](https://user-images.githubusercontent.com/12938082/191944711-610270f7-df38-444d-b3d1-68d21d225eaa.png)

All these problems could be solved manually but it would be nice if the solutions were built directly into modular so it is automatically handled and improves best practices.

**Comment by cristiano-belloni** [comment]
The two PRs have been merged, closing
