### ISSUE TITLE
Replace babel with ts-loader for transpilation

### ISSUE THREAD

**Issue by LukeSheard** [jpmorganchase/modular#221]
https://blog.johnnyreilly.com/2021/01/create-react-app-with-ts-loader-and-craco.html

I was reading this and it made me think about the issues that I've faced migrating projects to modular which are not using `isolatedModules: true`. If we were to replace babel-loader for typescript transpilation within `craco` for builds this would remove some of the issues that we've faced - since we are no longer limited to a subset of the TypeScript language.

I propose we do the change outlined in the post above to migrate to `ts-loader` so that we use `tsc` to transpile code instead of babel.

**Comment by threepointone** [comment]
Wr discussed this offline, but for posterity's sake: We should be going more towards transpilation, or even simply stripping types, and using typescript only for annotations and correctness/soundness. isolatedModules appears to be the right decision (even outside of CRA). So we should stick with babel (and indeed, move away from babel in the future towards simply stripping types and writing modern javascript).

For more, this is a pretty great post on the scaling aspect https://www.techatbloomberg.com/blog/10-insights-adopting-typescript-at-scale/

Closing this issue, thanks for bringing it up.

**Comment by NMinhNguyen** [comment]
> Wr discussed this offline, but for posterity's sake: We should be going more towards transpilation, or even simply stripping types, and using typescript only for annotations and correctness/soundness. isolatedModules appears to be the right decision (even outside of CRA). So we should stick with babel (and indeed, move away from babel in the future towards simply stripping types and writing modern javascript).
> 
> For more, this is a pretty great post on the scaling aspect [techatbloomberg.com/blog/10-insights-adopting-typescript-at-scale](https://www.techatbloomberg.com/blog/10-insights-adopting-typescript-at-scale/)
> 
> Closing this issue, thanks for bringing it up.

Didn't get round to commenting, but that's right. `isolatedModules` allows for parallelisation as files can be processed independently. And it's best to avoid runtime TS features like enums in case they ever land in ECMAScript where the spec might be different to TS's definition.
