### ISSUE TITLE
jest --injectGlobals=false

### ISSUE THREAD

**Issue by LukeSheard** [jpmorganchase/modular#234]
Following https://www.techatbloomberg.com/blog/10-insights-adopting-typescript-at-scale/ I had a thought about `jest` which we've come across internally in a couple of places. By default `jest` doesn't ship with any type declarations and so normally one immediately goes and installed `@types/jest` which declares all the globals required. However I wonder if we should default `--injectGlobals` to false to encourage people to use `@jest/globals` to use `describe`, `it`, etc... 

This should also help as the repo scales to type check as it removes the presence of the injected global environment which could potentially corrupt application files as well.

**Comment by threepointone** [comment]
This sounds good to me, provided we have a codemod that can add the required imports to existing tests.

**Comment by LukeSheard** [comment]
Something like this should work. 

```js
const GLOBALS = [
  "afterAll",
  "afterEach",
  "beforeAll",
  "beforeEach",
  "describe",
  "test"
];

// Press ctrl+space for code completion
export default function transformer(file, api) {
  const j = api.jscodeshift;

  const root = j(file.source);

  const expressions = [];
  root
    .find(j.ExpressionStatement, {
      expression: {
        type: "CallExpression"
      }
    })
    .forEach((c) => {
      const fn = c.value.expression.callee.name;
      if (GLOBALS.includes(fn)) {
        expressions.push(fn);
      }
    });
  
  root.find(j.Identifier, {
    name: "jest"
  }).forEach(i => {
    expressions.push("jest");
  });

  const imports = expressions.map(JSON.stringify).join(", ");
  const s = `import { ${imports} } from "@jest/globals";`;
  root.get().node.program.body.unshift(s);

  return root.toSource();
}
```
