### ISSUE TITLE
error: missing required argument 'name' while running yarn create modular-react-app

### ISSUE THREAD

**Issue by op1ekun** [jpmorganchase/modular#466]
When I run `yarn create modular-react-app <project-name>`  in my repo I get:
```
error: missing required argument 'name'
```

![image](https://user-images.githubusercontent.com/711524/121672843-2e989480-caa8-11eb-919f-fcdaf4f45f8e.png)
 
&nbsp;
  
Running `create-modular-react-app <project-name>` directly yields the same result.

![image](https://user-images.githubusercontent.com/711524/121673019-60a9f680-caa8-11eb-9f89-a5e09b451b8d.png)

Environment:
macOs Catalina 10.15.7
iTerm2 3.4.8
yarn 1.22.4

**Comment by LukeSheard** [comment]
This should be fixed in https://github.com/jpmorganchase/modular/releases/tag/create-modular-react-app%400.8.9 🥳
