### ISSUE TITLE
` yarn create modular-react-app` fails

### ISSUE THREAD

**Issue by zemeolotu** [jpmorganchase/modular#505]
` yarn create modular-react-app my-app` fails

<img width="991" alt="Screenshot 2021-06-27 at 12 22 25" src="https://user-images.githubusercontent.com/9936180/123552188-fef1b980-d742-11eb-9660-47860083678a.png">

Environment:
macOs Big Sur 11.0.1
node 12.18.3
yarn 1.21.1

**Comment by cangarugula** [comment]
Could check if there is a node_modules folder, yarn.lock file, or package-json.lock file in the directory you are running this command? You should delete those and try again.

A common issue as well is not having the required node version ("^12.13.0 || ^14.15.0 || >=15.0.0")

**Comment by LukeSheard** [comment]
This should be resolved in `v1.0.0` of `create-modular-react-app`
