### ISSUE TITLE
Debug and resolve why the E2E tests need `--forceExit` when run in a Docker container (or on CI)

### ISSUE THREAD

**Issue by sebinsua** [jpmorganchase/modular#54]
We should debug and resolve why the E2E tests need `--forceExit` when run in a Docker container (or on CI).

See the following comment for further information: https://github.com/jpmorganchase/modular/blob/1fd6cb2efe1bbfef5352447aad4761b04e16e9af/e2e-tests/core.test.ts#L154-L168

**Comment by threepointone** [comment]
Marking this as high pri, since it's been marked as skipped in our tests, and we should fix it soon.

**Comment by threepointone** [comment]
This issue isn't particularly accurate anymore since we've changed the way we run the tests and have a fresh set of problems. Closing this issue in favour of https://github.com/jpmorganchase/modular/issues/169.
