### ISSUE TITLE
Modular port for modular apps/views/packages

### ISSUE THREAD

**Issue by cangarugula** [jpmorganchase/modular#685]
`modular port` is currently set up to port over create-react-app repos but we need to work on how to move over modular workspaces. You could theoretically point the relative path further in the modular packages folder (e.g. `modular port ../another-modular-project/packages/my-modular-app`) but there are additional dependency resolution steps needed in order to make that port process seamless. This will be valuable when it comes time to consolidate modular mega repos.

**Comment by steveukx** [comment]
This currently falls outside of the core functionality for modular, combined with the decision to use `noExtraneousDependencies` lint rule ensuring the views have all dependencies specified means we will not be adding value other than copying over in the file system.
