### ISSUE TITLE
esbuild error on node 12

### ISSUE THREAD

**Issue by heswell** [jpmorganchase/modular#854]
supported engines include node "^12.13.0". However esbuild support for all v12 versions of node is broken by the following
```
import * as fs from “fs/promises” 
```
There are several occurrences of this across modular scripts, one example:
https://github.com/jpmorganchase/modular/blob/main/packages/modular-scripts/src/esbuild-scripts/api.ts#L1

it is easily fixed
https://github.com/nodejs/node/issues/35740#issuecomment-713778857

**Comment by LukeSheard** [comment]
There's already an open PR for this in #843 which is being merged today.
