### ISSUE TITLE
Configure `tsconfig.json` to only load `@types/node` for Node programs 

### ISSUE THREAD

**Issue by sebinsua** [jpmorganchase/modular#9]
Configure `tsconfig.json` to only load `@types/node` for Node programs, and not to pollute code which runs on the browser [with the following types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/globals.d.ts#L147).

Issue brought up in https://github.com/jpmorganchase/modular/pull/8#discussion_r428988654 and https://github.com/jpmorganchase/modular/pull/1#discussion_r428815379 (although the latter is more from ESLint's perspective).

I suspect ['solution-style `tsconfig.json`' are the right approach](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-rc/#solution-style-tsconfig) but these are very new so might lack support.

**Comment by threepointone** [comment]
We don't load @types/node at all, closing this.

**Comment by NMinhNguyen** [comment]
> We don't load @types/node at all, closing this.

That's incorrect. Most of the code in this repo is Node.js code (e.g. the CLI etc.) written in TypeScript, and it should be linted/type-checked accordingly.
