### ISSUE TITLE
lint/error against using webpack specific features in user code

### ISSUE THREAD

**Issue by threepointone** [jpmorganchase/modular#94]
We want to make sure we're not tied to any webpack specific APIs _in user code_, so we should figure out a way to disallow such usages. Eg: we probably shouldn't allow webpack's named chunks `import(/* webpackChunkName: "some-name" */ 'some-module')`

**Comment by cristiano-belloni** [comment]
Unfortunately, for now we need `/* webpackIgnore: true */` when we use webpack with esm-views that runtime import other esm-views, if they use webpack.
